### ISSUE TITLE
利用 Copr 构建社区 repo

### ISSUE THREAD

**Issue by tvvocold** [FZUG/idea#1]
案例：
https://github.com/RussianFedora/russianfedora-free-release
https://github.com/archlinuxcn/repo

打包项目征集：
可用 http://feathub.com/ 进行收集/vote.

**Comment by alick** [comment]
RussianFedora 看起来没有用 copr，而是类似 rpmfusion 的架构。

我觉得对于新包请求，github issues 已经足够，没必要上 feathub

**Comment by tvvocold** [comment]
OK
