### ISSUE TITLE
新版社区站

### ISSUE THREAD

**Issue by tvvocold** [FZUG/idea#2]
http://demo.fdzh.org/  征求大家意见

另，http://news.fdzh.org/ 也全新改版（新增 /ask 等模块，可能需要用户 Ctrl+F5 强制刷新浏览器缓存）

**Comment by tonghuix** [comment]
貌似 自由、友爱、杰出、前卫，这几个F开头的已经要求不翻译了吧？等其他人的想法吧，我觉得还是紧随Fedora官方要求的好，毕竟现在getfedora.org网页就没有翻译。

关于主题，我提个想法，咱们是否可以直接套用官方主页那种模板？以显的和官方一致性？当然这官方是没有要求的，咱们现在这样也挺好。

小问题：网页的favicon怎么是IF?

**Comment by tvvocold** [comment]
恩，那就不翻译了。https://github.com/fdzh/fdzh.github.io/commit/b290f74f16107560959b4357e7ce1162c21ed06d

Favicon是临时设计的，我在等新的社区 logo 出来。（不过我觉得 iF 也不错,取义为 “爱 Feodra”。）

官方好像不允许 Copy 吧。

**Comment by tonghuix** [comment]
那主题就不动了，保持现状，我觉得挺好。

还有个问题，能否加入邮件列表的链接，还有如何下载Fedora以及官方wiki的链接。

**Comment by tvvocold** [comment]
在底部啊

**Comment by tvvocold** [comment]
最新修改版：http://demo.fdzh.org/ （同步了文章等内容）
欢迎提出建议/PR
