### ISSUE TITLE
Copr 服务器续期

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/idea#3]
Copr 服务器即将到期，5月10日进行下一次续费。
如果不能申请到 ucloud 赞助，则将服务器删除，使用 http/ftp 托管社区 rpm 包。
届时，剩余的资金还可以维持 3-4 个月。

**Comment by tvvocold** [comment]
先暂缓，等我确定消息。

**Comment by alick** [comment]
copr 服务事实上已经下线
