### ISSUE TITLE
源审查建议

### ISSUE THREAD

**Issue by 1dot75cm** [FZUG/idea#4]
鉴于社区源审查较为缓慢，我建议加快合并开源软件（源里的 rpm 已经都在 fc22 测试通过了）。
闭源软件等待获得版权人许可，再合并。

**Comment by tvvocold** [comment]
+1

**Comment by alick** [comment]
加快合并开源软件是指什么？合并到哪？

**Comment by alick** [comment]
我是觉得我们源审查的流程应该简化，不需要那么正式。

**Comment by 1dot75cm** [comment]
> 加快合并开源软件是指什么？合并到哪？

合并到 FZUG/repo 里。

> 我是觉得我们源审查的流程应该简化，不需要那么正式。

嗯嗯，审查软件协议只要是开源的就可以，闭源的需要“商量”一下。

**Comment by alick** [comment]
考虑到目前的状态（审查软件人员有限），我觉得 @1dot75cm 的“审查软件时只要是开源软件就放行”的主意OK。 @FZUG/tier1 都发表下观点？

**Comment by cicku** [comment]
开源的没什么问题，按照 Fedora Legal 认可的协议来合并就可以了。不承认的开源协议另当回事。

**Comment by 1dot75cm** [comment]
> 不承认的开源协议另当回事。

有哪些不承认的开源协议？

**Comment by alick** [comment]
Fedora 官方认可的许可证列表：https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Software_License_List
