### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by tvvocold** [FZUG/idea#5]
hi @FZUG/tier1 ,
既然社区线上线下活动很多，为什么不新建一个仓库存放活动信息呢？（包括线上/线下，即将开始/已经结束，我们社区/其他社区的）。
这样大家就可以点击 Watch 进行关注并参与了。

例：https://github.com/offlinefirst/events

**Comment by 1dot75cm** [comment]
嗯嗯， 活动一般都写在 wiki？ github可以放一些活动的 ppt doc 之类的。

**Comment by tvvocold** [comment]
wiki怎么订阅？

**Comment by alick** [comment]
wiki 没有订阅，不过可以“监视“页面。

2015-07-12 0:14 GMT+08:00 Ray notifications@github.com:

**Comment by tvvocold** [comment]
恩，多个地点推送也不是坏事，特别是活动类等需要宣传的信息。

**Comment by alick** [comment]
嗯，宣传主要靠SNS

2015-07-12 22:51 GMT+08:00 Ray notifications@github.com:

**Comment by tvvocold** [comment]
宣传的话，我觉得面向开发人员，在 Github 搞也很不错的，先试试吧。
