### ISSUE TITLE
新手指南

### ISSUE THREAD

**Issue by tvvocold** [FZUG/idea#6]
刚看到 https://github.com/zpj-ustc/openSUSE-novice-guide 觉得很赞,
fc22 的 [doc](http://docs.fedoraproject.org/en-US/Fedora/22/html/Installation_Guide/index.html) 至今也没中文版，不如我们一起维护一个（本土化的）新手指南？

**Comment by Endle** [comment]
可以加入翻译组
参见 https://fedoraproject.org/wiki/L10N/Guide
具体的翻译相关问题在邮件列表里讨论吧

**Comment by tvvocold** [comment]
我个人希望能 create 一个而不是 fork 官方的。本土化

**Comment by Endle** [comment]
不清楚造轮子有什么意义
如果你觉得原有的网站用起来不方便的话，我建议也是把翻译提交上去，然后用脚本把翻译抓取下来，导出成想要的格式

2015-07-30 15:19 GMT+08:00 Ray notifications@github.com:

> 我个人希望能 create 一个而不是 fork 官方的。本土化
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FZUG/idea/issues/6#issuecomment-126207580.

## 

Have a nice day!
Zhenbo Li

**Comment by sztsian** [comment]
> 我个人希望能 create 一个而不是 fork 官方的。本土化

很高兴你能提出关于本地化的问题。

我认为Endle说的对。我们需要做的是推进现有内容的翻译，而不是从0撰写内容。

也许后面的回复比较歪楼。个人认为，中国大陆的社区已经足够、甚至过于“本土化”了。APAC Community Manager提出了对中国大陆的Fedora社区的不满，主要原因就是因为我们贡献者少，贡献也少。这也是大家一直努力要扭转的问题。大家都是业余在为社区做贡献，想必白天的工作都已经很忙了，业余时间继续拆分到更“本土化”的项目中，我担心将来连Release Party都搞不成了。希望你能理解我的看法。

**Comment by tvvocold** [comment]
@FZUG/tier1 
我们是不是应该启动一个拉新计划？

**Comment by alick** [comment]
眼下我们应该搞好我们的发行派对。

2015-07-30 20:39 GMT+08:00 Ray notifications@github.com:

**Comment by Endle** [comment]
所以不要歪楼了。
如何拉新人，如何办好发行派对都是很值得探讨的话题，个人建议再开一个新 Issue

**Comment by tvvocold** [comment]
OK，party 要不要写个 repo？
https://github.com/FZUG/idea/issues/5

**Comment by sztsian** [comment]
Rel Party我觉得暂时没必要专门做个Repo。在时间和地点确定后，其他的事情基本都是公开在邮件列表里讨论或者在会议上讨论的。这个线索我就不再回复了。
