### ISSUE TITLE
Check this

### ISSUE THREAD

**Issue by tvvocold** [FZUG/idea#7]
hi @FZUG/tier1 ,
Check this: http://upgradefromwindows.com

**Comment by tvvocold** [comment]
@sztsian 
如果 fdzh.org 汉化并发表这个，会不会收到 MS 的律师函？

**Comment by cicku** [comment]
I don't have any interests on this page, I'm a Win10 loyal user.

**Comment by cicku** [comment]
Meanwhile I don't want to turn FZUG as a group of radical, aggressive and pedantic fogies. FSF and GNU have translation teams to handle contents they want to translate.

**Comment by gbraad** [comment]
Thanks. the difference between FSF and Open Source 'believes' can sometimes
turn into a nasty food/pillow fight which we should remain far away from if
possible. I agree that it is up to the organizations themselves to
translate and handle such content.
