### ISSUE TITLE
關於更新FZUG的logo

### ISSUE THREAD

**Issue by ghost** [FZUG/idea#8]
個人感覺現在的FZUG的logo設計有些old school，所以在這裡提議更新FZUG的logo。換一個更modern點兒的。

歡迎大家在這裡討論下對現有FZUG的logo的看法和意見。如果認同『需要更新』，也歡迎提出新logo設計式樣。

我先提個logo設計式樣：
![fzug2](https://cloud.githubusercontent.com/assets/13869410/18908155/db365e34-85b1-11e6-98d6-caee77345073.png)

**Comment by tonghuix** [comment]
很漂亮，但是我略有点担心会不会不符合官方标准？

https://fedoraproject.org/wiki/Logo/UsageGuidelines
https://fedoraproject.org/wiki/Legal:Trademark_guidelines

**Comment by 1dot75cm** [comment]
喔，Cool，我喜欢这个设计 :+1:

**Comment by ghost** [comment]
@tonghuix 

 你是指這句話麼？

> Do not attempt to redraw the logos or otherwise recreate them. This could result in unauthorized logo variations getting spread around, and although we know your intentions are quite good, this will cause problems that are difficult to resolve. Be smart, and use the right logos!

這是防止人們覺得現有logo丑，然後修改，從而導致修改過的Fedora logo被傳播。

剛才跟 @1dot75cm 討論了下，他理解成了『不能對Fedora的logo作修改』。其實如果非要按這樣理解，那麼現有的logo就不應該被允許。

另外找了Fedora Russia的logo做了下Usage Guidelines參考，如圖：

![Fedora Russia](http://ru.fedoracommunity.org/sites/default/files/rflogo.png)

這樣的logo也包含了Fedora的logo，按『不能對Fedora的logo作修改』的說法，這也是不對的，除非分開變成兩張圖片。而且這張圖片還加了陰影，相比之下，我先提的logo設計式樣應該更符合標準點兒。

**Comment by sztsian** [comment]
如果不考虑是否获得了lega批准，仅就设计而言，Fedora Russian 的 logo 是完全符合 Logo Guideline 的。因为它以正确的方式保留了完整的 Fedora Logo （infinite图案和Fedora文字），且背景颜色与前景色区分明显，而且 logo 外具有足够大的留白区域。而当前在使用的 FZUG logo 已经多次被 Board 等机构指出其不正确之处。[2014年8月](https://lists.fedoraproject.org/archives/list/chinese@lists.fedoraproject.org/thread/VJIFWZMMPE4RLB3ZGEBBLVT7CP7TEIMM/) 和 [2015年3月](https://lists.fedoraproject.org/archives/list/chinese@lists.fedoraproject.org/thread/7YHRPBKDDOECFIHPA3WJQKVZ5FLOVNL5/) 曾分别讨论过关于重新设计Logo。并且 @cicku 应该也为此与人联系过（不知道有下文么）。如果我们真的有必要重新设计Logo，那么我们不妨在上次讨论的基础上做，且要向legal获得logo的使用许可。

**Comment by ghost** [comment]
所以總結下來就是，感覺可以在下面三個方案選一個：
- 根據Usage Guidelines重新設計一個logo
- 設計一個純『FZUG』文字的logo
- 直接使用Fedora官方logo

**Comment by tonghuix** [comment]
我认为第二种方案更好，但是从安全角度出发，最好是用官方logo，然后补上中文既可。

**Comment by cicku** [comment]
我不太想管这个事情了，精力有限。

**Comment by ghost** [comment]
舉手，咱覺得，有必要更換，不過乾脆『直接使用Fedora官方logo』得了（以解決現有logo不妥當問題）。
![fzug-logo3](https://cloud.githubusercontent.com/assets/13869410/18937783/ca14384e-8636-11e6-9561-a0a9a476b533.png)

畢竟『当前在使用的 FZUG logo 已经多次被 Board 等机构指出其不正确之处』，而且大家基本都是搞技術的，想了想，感覺就算專門花時間去討論和研修一個新logo式樣，可能也討論不出什麼結果出來。

倒是建議，如果有todo list的話，可以把這個議題加進去，如果以後有搞design的成員加入並且願意專門設計一個FZUG自己的logo話，再做更換。

PS：剛才嘗試設計了一個純『FZUG』文字的logo，感覺丑哭了，哈哈哈

![fzug-logo2](https://cloud.githubusercontent.com/assets/13869410/18937877/93d2af80-8637-11e6-8998-1d85e8100ce0.png)

**Comment by Endle** [comment]
> 如果不考虑是否获得了lega批准，仅就设计而言，Fedora Russian 的 logo 是完全符合 Logo Guideline 的。因为它以正确的方式保留了完整的 Fedora Logo （infinite图案和Fedora文字），且背景颜色与前景色区分明显，而且 logo 外具有足够大的留白区域。

那我们就效仿他们做一个呢？把FZUG放到logo下面

**Comment by cicku** [comment]
我就强调一点，如何设计一个能反映 FZUG 的 logo 是当务之急，带不带 Fedora 的 logo 并不是很重要。

**Comment by tonghuix** [comment]
给github头像用，@nrechn 简单的FZUG的这个设计就挺好

**Comment by ghost** [comment]
> 而当前在使用的 FZUG logo 已经多次被 Board 等机构指出其不正确之处。

既然當前的logo不正確(不符合規範)，那麼現在優先考慮的應該是更換一個完全符合Logo Guideline的logo。

看了下[2014年8月](https://lists.fedoraproject.org/archives/list/chinese@lists.fedoraproject.org/thread/VJIFWZMMPE4RLB3ZGEBBLVT7CP7TEIMM/)和[2015年3月](https://lists.fedoraproject.org/archives/list/chinese@lists.fedoraproject.org/thread/7YHRPBKDDOECFIHPA3WJQKVZ5FLOVNL5/)的maillist，我覺得這次討論不能再像之前兩次那樣無限期拖下去了。乾脆現在統一使用Fedora官方logo（考慮到目前沒人有能力/精力去專門設計一個精緻的FZUG的logo）。

如果未來有人提供了FZUG自己logo的設計，可以經過投票一致同意後進行統一更換。

**Comment by ghost** [comment]
> 我就强调一点，如何设计一个能反映 FZUG 的 logo 是当务之急，带不带 Fedora 的 logo 并不是很重要。

設計一個能反映FZUG的logo固然重要，但是根據maillist裡的討論，目前已經聯繫不上設計現用logo的人了，同時現在暫時沒有人有精力自己設計或者有時間去專門請人設計。所以不妨先更換Fedora官方logo(暫時)使用。如果有人提供了能反映FZUG的logo，再進行更換。

PS: 鑑於現在的logo不符合Fedora Logo Guideline，同時這個問題也被別人指出了不符合規範。放任繼續保持現有的logo感覺算是一種對Fedora官方不尊重的行為。

**Comment by sztsian** [comment]
先用Fedora官方logo吧。

**Comment by alick** [comment]
等等，如果是在说 github 上这个在组织的 logo，直接用 fedora logo 似乎不妥，会给人误解。

**Comment by alick** [comment]
github fzug 组织的 logo 不符合 guideline，有权限的麻烦先撤掉吧。 @sztsian @cicku ?

**Comment by alick** [comment]
ping @sztsian @cicku

**Comment by ghost** [comment]
所以說，有權限的兩位，你們看法如何？ @sztsian @cicku 

如果始終沒人繼續討論，我擔心這個問題將再次不了了之。

**Comment by sztsian** [comment]
抱歉把这事忘了。
![fzug](https://cloud.githubusercontent.com/assets/5670072/19374471/61f66a92-91fe-11e6-9432-263cd4515e98.png)
我先做了这个logo贴上。

**Comment by sztsian** [comment]
已经更换。看起来需要一些时间才能在Github 的 CDN上同步好。

**Comment by alick** [comment]
不错。不过zsun这个里面的 F 看着有点怪，特别窄 
🤔

**Comment by sztsian** [comment]
我使用的MgOpen Modata Regular， 与 [Logo](https://fedoraproject.org/wiki/Logo#FUDCon_Logo) 页面要求FUDCon使用的字体是一致的。

如果觉得不好看，似乎还可以考虑 [Comfortaa](https://fedoraproject.org/wiki/Logo/UsageGuidelines#Comfortaa)

**Comment by ghost** [comment]
我覺得 Comfortaa 會更好看點兒

**Comment by sztsian** [comment]
已换为Comfortaa
![fzug](https://cloud.githubusercontent.com/assets/5670072/19424572/c2f46cf8-945c-11e6-9fc5-6de175f32283.png)

**Comment by alick** [comment]
赞。https://fedoraproject.org/wiki/Zh 这里的我也更新了。如果有更高清大图请再做更新。

**Comment by sztsian** [comment]
> 赞。https://fedoraproject.org/wiki/Zh 这里的我也更新了。如果有更高清大图请再做更新。

其实啥都没改，就是纯粹的Inkscape文字（
